# bowtie/ssh-tunnel - Basic Example
version: '3.5'

services:
  ssh-tunnel:
    image: bowtie/ssh-tunnel
    # build: .
    ports:
      - 3333:3306
    volumes:
      - ~/.ssh:/home/user/.ssh
    environment:
      ##################################
      # Required environment variables #
      ##################################
      SSH_USER: username
      SSH_HOST: ssh-bastion-host.example.com
      REMOTE_HOST: mysql-database-host.example.private
      REMOTE_PORT: 3306

      ##################################
      # Optional environment variables # (showing default values below)
      ##################################
      # SSH_KEY: id_rsa
      # SSH_PORT: 22
      # SSH_PATH: /home/user/.ssh
      # SSH_CONF: $SSH_PATH/tunnel_config
      # BIND_HOST: '0.0.0.0'
      # BIND_PORT: $REMOTE_PORT
      # VERBOSE: 'true'
      # PING_WAIT: 30