version: '3.5'

services:
  ssh-tunnel:
    # image: bowtie/ssh-tunnel
    build: .
    ports:
      - 3333:3307
    volumes:
      - ~/.ssh:/home/user/.ssh
    environment:
      SSH_KEY: example-dev
      SSH_USER: example-dev
      SSH_HOST: ssh-use1.staging.usacycling.org
      SSH_PORT: 22
      BIND_HOST: 0.0.0.0
      BIND_PORT: 3307
      REMOTE_HOST: usac-db-mysql-staging.clj0ec3twiv7.us-east-1.rds.amazonaws.com
      REMOTE_PORT: 3306
      VERBOSE: 'true'
      PING_WAIT: 30
