version: '3.5'

services:
  ssh-tunnel:
    image: bowtie/ssh-tunnel
    # build: .
    ports:
      - 3333:3307
    volumes:
      - ./.ssh:/home/user/.ssh
    environment:
      SSH_USER: charlie
      SSH_HOST: ssh-use1.staging.usacycling.org
      SSH_PORT: 22
      LOCAL_HOST: 0.0.0.0
      LOCAL_PORT: 3307
      REMOTE_HOST: usac-db-mysql-staging.clj0ec3twiv7.us-east-1.rds.amazonaws.com
      REMOTE_PORT: 3306
      # VERBOSE: 'true'
      PING_WAIT: 5
